# Generated by Django 5.0.14 on 2026-07-13 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('partial_credit', models.BooleanField(default=False)),
                ('negative_marking', models.BooleanField(default=False)),
                ('per_option_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'scoring policy',
                'verbose_name_plural': 'scoring policies',
            },
        ),
        migrations.CreateModel(
            name='ObjectiveScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_id', models.CharField(db_index=True, max_length=64)),
                ('question_id', models.CharField(db_index=True, max_length=64)),
                ('question_version', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fib', 'Fill in the Blank'), ('multi_select', 'Multi Select')], max_length=32)),
                ('awarded_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_correct', models.BooleanField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'objective score',
                'verbose_name_plural': 'objective scores',
                'indexes': [models.Index(fields=['attempt_id', 'question_id'], name='grading_obj_attempt_fb6f5c_idx')],
            },
        ),
    ]
