# Generated by Django 5.0.14 on 2026-07-13 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('test_id', models.CharField(db_index=True, max_length=64)),
                ('total_awarded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('by_topic', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'combined result',
                'verbose_name_plural': 'combined results',
            },
        ),
        migrations.CreateModel(
            name='TestConfigSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('passing_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pass_type', models.CharField(choices=[('absolute', 'Absolute'), ('percent', 'Percent')], default='absolute', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'test config snapshot',
                'verbose_name_plural': 'test config snapshots',
            },
        ),
        migrations.CreateModel(
            name='FreeTextQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_id', models.CharField(db_index=True, max_length=64)),
                ('test_id', models.CharField(db_index=True, max_length=64)),
                ('question_id', models.CharField(db_index=True, max_length=64)),
                ('question_version', models.CharField(blank=True, max_length=32, null=True)),
                ('candidate_display', models.CharField(blank=True, max_length=255, null=True)),
                ('blind_marking', models.BooleanField(default=False)),
                ('response_text', models.TextField()),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('topic', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('graded', 'Graded')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'free text queue item',
                'verbose_name_plural': 'free text queue items',
                'indexes': [models.Index(fields=['status', 'test_id'], name='grading_fre_status_fe6f7f_idx'), models.Index(fields=['attempt_id', 'question_id'], name='grading_fre_attempt_a0e2da_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManualGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grader_user_id', models.IntegerField()),
                ('awarded_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_grade', to='grading.freetextqueueitem')),
            ],
            options={
                'verbose_name': 'manual grade',
                'verbose_name_plural': 'manual grades',
            },
        ),
    ]
