# Generated by Django 5.0.14 on 2026-07-14 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(db_index=True, max_length=128)),
                ('topic', models.CharField(db_index=True, max_length=128)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=16)),
                ('type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI_SELECT', 'Multi Select'), ('TRUE_FALSE', 'True/False'), ('FILL_IN_BLANK', 'Fill in the Blank'), ('FREE_TEXT', 'Free Text')], db_index=True, max_length=32)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('points', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=8)),
                ('value', models.CharField(max_length=512)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.question')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BlankAnswerKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=512)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_answer_keys', to='question_bank.question')),
            ],
            options={
                'ordering': ['answer'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'topic'], name='question_ba_subject_b523a0_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type', 'difficulty'], name='question_ba_type_b6d21f_idx'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'label'), name='unique_option_label_per_question'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_option_value_per_question'),
        ),
        migrations.AddConstraint(
            model_name='blankanswerkey',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='unique_blank_answer_per_question'),
        ),
    ]
