# Generated by Django 5.0.14 on 2026-07-14 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=128)),
                ('topic', models.CharField(max_length=128)),
                ('difficulty', models.CharField(max_length=16)),
                ('question_type', models.CharField(max_length=32)),
                ('prompt', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('options', models.JSONField(default=list)),
                ('correct_answers', models.JSONField(default=list)),
                ('sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_versions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='question_bank.question')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['question', 'version_number'], name='question_ba_questio_1e11dd_idx')],
                'unique_together': {('question', 'version_number')},
            },
        ),
    ]
