# Generated by Django 5.0.14 on 2026-07-14 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('html_body', models.TextField(blank=True, default='')),
                ('text_body', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_email_template',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('template_key', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('throttled', 'Throttled')], db_index=True, default='pending', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('assignment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('test_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('triggered_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_email_message_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['template_key', 'assignment_id', 'sent_at'], name='notificatio_templat_d90dfe_idx'), models.Index(fields=['template_key', 'test_id', 'sent_at'], name='notificatio_templat_7e1b35_idx')],
            },
        ),
    ]
