# Generated by Django 5.0.14 on 2026-07-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id', models.CharField(blank=True, default='', max_length=255)),
                ('actor_display', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
