# Generated by Django 5.0.14 on 2026-07-14 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0002_question_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, default='', max_length=128)),
                ('topic', models.CharField(blank=True, default='', max_length=128)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='', max_length=16)),
                ('question_type', models.CharField(blank=True, choices=[('MCQ', 'Multiple Choice'), ('MULTI_SELECT', 'Multi Select'), ('TRUE_FALSE', 'True/False'), ('FILL_IN_BLANK', 'Fill in the Blank'), ('FREE_TEXT', 'Free Text')], default='', max_length=32)),
                ('count', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests.test')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rule')], default='manual', max_length=16)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_links', to='question_bank.question')),
                ('question_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_links', to='question_bank.questionversion')),
                ('selection_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_links', to='tests.selectionrule')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='tests.testsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='selectionrule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_rules', to='tests.testsection'),
        ),
        migrations.CreateModel(
            name='TestShuffleSeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed_type', models.CharField(choices=[('questions', 'Questions'), ('options', 'Options')], max_length=16)),
                ('seed_value', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shuffle_seeds', to='tests.test')),
            ],
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['lifecycle', 'created_at'], name='tests_test_lifecyc_661b5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='testsection',
            constraint=models.UniqueConstraint(fields=('test', 'order'), name='unique_section_order_per_test'),
        ),
        migrations.AddConstraint(
            model_name='testquestionlink',
            constraint=models.UniqueConstraint(fields=('section', 'question'), name='unique_question_per_section'),
        ),
        migrations.AddConstraint(
            model_name='selectionrule',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_rule_order_per_section'),
        ),
        migrations.AddConstraint(
            model_name='testshuffleseed',
            constraint=models.UniqueConstraint(fields=('test', 'seed_type'), name='unique_shuffle_seed_type_per_test'),
        ),
    ]
