# Generated by Django 5.0.14 on 2026-07-14 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_id', models.UUIDField(db_index=True)),
                ('assignee_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('assignee_group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_user_id', models.UUIDField(db_index=True)),
                ('opens_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_assignment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['test_id', 'status'], name='core_assign_test_id_b5ff00_idx'), models.Index(fields=['opens_at', 'closes_at'], name='core_assign_opens_a_3d4639_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('test_id', 'assignee_user_id'), name='core_assignment_unique_test_user'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('test_id', 'assignee_group_id'), name='core_assignment_unique_test_group'),
        ),
    ]
